# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA07/ThaiAn/Python-app/ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 0, 71, 81))
        font = QtGui.QFont()
        font.setFamily("Parkinsans Medium")
        self.pushButton.setFont(font)
        self.pushButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton.setStyleSheet("    background-image: url(\'netflix-logo.png\'); /* Netflix logo */\n"
"    background-repeat: no-repeat;\n"
"    background-size: contain;\n"
"    width: 100px;  /* Set appropriate width */\n"
"    height: 30px;  /* Set appropriate height */\n"
"\n"
"")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/ThaiAn/Python-app/ui/../img/LOGO.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(150, 150))
        self.pushButton.setObjectName("pushButton")
        self.nav_movie_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.nav_movie_btn.setGeometry(QtCore.QRect(220, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setBold(True)
        self.nav_movie_btn.setFont(font)
        self.nav_movie_btn.setStyleSheet("QPushButton {\n"
"    background-color: black;       /* Black background */\n"
"    border: 2px solid solid; /* Transparent border by default */\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;            /* Rounded corners */\n"
"    padding: 10px;                 /* Default padding */\n"
"    background-repeat: no-repeat; /* No repeating the image */\n"
"    background-position: center;  /* Center the icon */\n"
"    transition: all 0.2s ease;    /* Smooth transition */\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid white;       /* White border on hover */\n"
"    padding: 8px;                  /* Reduced padding to simulate size increase */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #333333;     /* Darker background on press */\n"
"    padding: 6px;                  /* Further reduced padding for pressed state */\n"
"}\n"
"")
        self.nav_movie_btn.setObjectName("nav_movie_btn")
        self.btn_mylist_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_mylist_btn.setGeometry(QtCore.QRect(340, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setBold(True)
        self.btn_mylist_btn.setFont(font)
        self.btn_mylist_btn.setStyleSheet("QPushButton {\n"
"    background-color: black;       /* Black background */\n"
"    border: 2px solid solid; /* Transparent border by default */\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;            /* Rounded corners */\n"
"    padding: 10px;                 /* Default padding */\n"
"    background-repeat: no-repeat; /* No repeating the image */\n"
"    background-position: center;  /* Center the icon */\n"
"    transition: all 0.2s ease;    /* Smooth transition */\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid white;       /* White border on hover */\n"
"    padding: 8px;                  /* Reduced padding to simulate size increase */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #333333;     /* Darker background on press */\n"
"    padding: 6px;                  /* Further reduced padding for pressed state */\n"
"}\n"
"")
        self.btn_mylist_btn.setObjectName("btn_mylist_btn")
        self.btn_search = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_search.setGeometry(QtCore.QRect(950, 10, 61, 61))
        self.btn_search.setAutoFillBackground(False)
        self.btn_search.setStyleSheet("QPushButton {\n"
"    background-color: black;       /* Black background */\n"
"    border: 2px solid transparent; /* Transparent border by default */\n"
"    border-radius: 5px;            /* Rounded corners */\n"
"    padding: 10px;                 /* Default padding */\n"
"    background-repeat: no-repeat; /* No repeating the image */\n"
"    background-position: center;  /* Center the icon */\n"
"    transition: all 0.2s ease;    /* Smooth transition */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid white;       /* White border on hover */\n"
"    padding: 8px;                  /* Reduced padding to simulate size increase */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #333333;     /* Darker background on press */\n"
"    padding: 6px;                  /* Further reduced padding for pressed state */\n"
"}\n"
"")
        self.btn_search.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/ThaiAn/Python-app/ui/../img/iconizer-magnifying-glass-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_search.setIcon(icon1)
        self.btn_search.setIconSize(QtCore.QSize(30, 30))
        self.btn_search.setObjectName("btn_search")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 80, 1001, 651))
        self.stackedWidget.setObjectName("stackedWidget")
        self.Movies = QtWidgets.QWidget()
        self.Movies.setObjectName("Movies")
        self.video_container = QtWidgets.QWidget(parent=self.Movies)
        self.video_container.setGeometry(QtCore.QRect(0, 10, 1001, 651))
        self.video_container.setStyleSheet("/* Movie Item Styles */\n"
".MovieItemWidget {\n"
"    background-color: black;\n"
"    border: 1px solid rgba(255, 255, 255, 0.8);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
".MovieItemWidget QLabel {\n"
"    color: white;\n"
"    font-family: Geist;\n"
"}\n"
"\n"
".MovieItemWidget .title {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
".MovieItemWidget .description {\n"
"    font-size: 12px;\n"
"}\n"
"\n"
".MovieItemWidget .overlay {\n"
"    background-color: rgba(0, 0, 0, 0.7);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
".MovieItemWidget .play-button {\n"
"    background-color: rgb(229, 9, 20);\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    padding: 8px;\n"
"    min-width: 40px;\n"
"    min-height: 40px;\n"
"}\n"
"\n"
".MovieItemWidget .play-button:hover {\n"
"    background-color: rgb(193, 17, 25);\n"
"}\n"
"\n"
".MovieItemWidget .control-button {\n"
"    background-color: rgba(42, 42, 42, 0.7);\n"
"    border: 1px solid rgba(255, 255, 255, 0.7);\n"
"    border-radius: 20px;\n"
"    padding: 8px;\n"
"    min-width: 40px;\n"
"    min-height: 40px;\n"
"}\n"
"\n"
".MovieItemWidget .control-button:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}")
        self.video_container.setObjectName("video_container")
        self.stackedWidget.addWidget(self.Movies)
        self.Detail = QtWidgets.QWidget()
        self.Detail.setObjectName("Detail")
        self.header = QtWidgets.QWidget(parent=self.Detail)
        self.header.setGeometry(QtCore.QRect(0, 0, 1001, 60))
        self.header.setStyleSheet("background-color: rgba(0, 0, 0, 0.7);")
        self.header.setObjectName("header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_back = QtWidgets.QPushButton(parent=self.header)
        self.btn_back.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_back.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_back.setStyleSheet("QPushButton {\n"
"    background-color: rgba(42, 42, 42, 0.7);\n"
"    border: 1px solid rgba(255, 255, 255, 0.7);\n"
"    border-radius: 20px;\n"
"    padding: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}")
        self.btn_back.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/ThaiAn/Python-app/ui/../img/arrow-left-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_back.setIcon(icon2)
        self.btn_back.setIconSize(QtCore.QSize(24, 24))
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout.addWidget(self.btn_back)
        self.btn_favorite = QtWidgets.QPushButton(parent=self.header)
        self.btn_favorite.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_favorite.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_favorite.setStyleSheet("QPushButton {\n"
"    background-color: rgba(42, 42, 42, 0.7);\n"
"    border: 1px solid rgba(255, 255, 255, 0.7);\n"
"    border-radius: 20px;\n"
"    padding: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}")
        self.btn_favorite.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/ThaiAn/Python-app/ui/../img/heart-regular.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_favorite.setIcon(icon3)
        self.btn_favorite.setIconSize(QtCore.QSize(24, 24))
        self.btn_favorite.setObjectName("btn_favorite")
        self.horizontalLayout.addWidget(self.btn_favorite)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lbl_detail_image = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_image.setGeometry(QtCore.QRect(60, 20, 300, 400))
        self.lbl_detail_image.setStyleSheet("border: 1px solid rgba(255, 255, 255, 0.8);\n"
"border-radius: 15px;\n"
"background-color: rgb(0, 0, 0);")
        self.lbl_detail_image.setObjectName("lbl_detail_image")
        self.lbl_detail_name = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_name.setGeometry(QtCore.QRect(400, 20, 581, 41))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(24)
        font.setBold(True)
        self.lbl_detail_name.setFont(font)
        self.lbl_detail_name.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_detail_name.setObjectName("lbl_detail_name")
        self.lbl_detail_director = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_director.setGeometry(QtCore.QRect(400, 80, 581, 31))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.lbl_detail_director.setFont(font)
        self.lbl_detail_director.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_detail_director.setObjectName("lbl_detail_director")
        self.lbl_detail_release_date = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_release_date.setGeometry(QtCore.QRect(400, 120, 581, 31))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.lbl_detail_release_date.setFont(font)
        self.lbl_detail_release_date.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_detail_release_date.setObjectName("lbl_detail_release_date")
        self.lbl_detail_genre = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_genre.setGeometry(QtCore.QRect(400, 160, 581, 31))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.lbl_detail_genre.setFont(font)
        self.lbl_detail_genre.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_detail_genre.setObjectName("lbl_detail_genre")
        self.lbl_detail_rating = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_rating.setGeometry(QtCore.QRect(400, 200, 581, 31))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.lbl_detail_rating.setFont(font)
        self.lbl_detail_rating.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_detail_rating.setObjectName("lbl_detail_rating")
        self.lbl_detail_duration = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_duration.setGeometry(QtCore.QRect(400, 240, 581, 31))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.lbl_detail_duration.setFont(font)
        self.lbl_detail_duration.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_detail_duration.setObjectName("lbl_detail_duration")
        self.lbl_detail_age_rating = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_age_rating.setGeometry(QtCore.QRect(400, 280, 581, 31))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.lbl_detail_age_rating.setFont(font)
        self.lbl_detail_age_rating.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_detail_age_rating.setObjectName("lbl_detail_age_rating")
        self.lbl_detail_main_actor = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_main_actor.setGeometry(QtCore.QRect(400, 320, 581, 31))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.lbl_detail_main_actor.setFont(font)
        self.lbl_detail_main_actor.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_detail_main_actor.setObjectName("lbl_detail_main_actor")
        self.lbl_detail_description = QtWidgets.QLabel(parent=self.Detail)
        self.lbl_detail_description.setGeometry(QtCore.QRect(400, 360, 581, 181))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.lbl_detail_description.setFont(font)
        self.lbl_detail_description.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_detail_description.setWordWrap(True)
        self.lbl_detail_description.setObjectName("lbl_detail_description")
        self.btn_play_video = QtWidgets.QPushButton(parent=self.Detail)
        self.btn_play_video.setGeometry(QtCore.QRect(60, 440, 300, 41))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setBold(True)
        self.btn_play_video.setFont(font)
        self.btn_play_video.setStyleSheet("QPushButton {\n"
"    background-color: rgb(229, 9, 20); /* Netflix red */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(193, 17, 25); /* Darker red on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(148, 0, 0); /* Even darker red when pressed */\n"
"}")
        self.btn_play_video.setObjectName("btn_play_video")
        self.stackedWidget.addWidget(self.Detail)
        self.My_List = QtWidgets.QWidget()
        self.My_List.setObjectName("My_List")
        self.label_10 = QtWidgets.QLabel(parent=self.My_List)
        self.label_10.setGeometry(QtCore.QRect(0, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.favorite_container = QtWidgets.QWidget(parent=self.My_List)
        self.favorite_container.setGeometry(QtCore.QRect(0, 60, 1001, 591))
        self.favorite_container.setStyleSheet("/* Movie Item Styles */\n"
".MovieItemWidget {\n"
"    background-color: black;\n"
"    border: 1px solid rgba(255, 255, 255, 0.8);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
".MovieItemWidget QLabel {\n"
"    color: white;\n"
"    font-family: Geist;\n"
"}\n"
"\n"
".MovieItemWidget .title {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
".MovieItemWidget .description {\n"
"    font-size: 12px;\n"
"}\n"
"\n"
".MovieItemWidget .overlay {\n"
"    background-color: rgba(0, 0, 0, 0.7);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
".MovieItemWidget .play-button {\n"
"    background-color: rgb(229, 9, 20);\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    padding: 8px;\n"
"    min-width: 40px;\n"
"    min-height: 40px;\n"
"}\n"
"\n"
".MovieItemWidget .play-button:hover {\n"
"    background-color: rgb(193, 17, 25);\n"
"}\n"
"\n"
".MovieItemWidget .control-button {\n"
"    background-color: rgba(42, 42, 42, 0.7);\n"
"    border: 1px solid rgba(255, 255, 255, 0.7);\n"
"    border-radius: 20px;\n"
"    padding: 8px;\n"
"    min-width: 40px;\n"
"    min-height: 40px;\n"
"}\n"
"\n"
".MovieItemWidget .control-button:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}")
        self.favorite_container.setObjectName("favorite_container")
        self.stackedWidget.addWidget(self.My_List)
        self.MediaPlayer = QtWidgets.QWidget()
        self.MediaPlayer.setObjectName("MediaPlayer")
        self.videoWidget = QtWidgets.QWidget(parent=self.MediaPlayer)
        self.videoWidget.setGeometry(QtCore.QRect(0, 0, 1001, 520))
        self.videoWidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.videoWidget.setObjectName("videoWidget")
        self.durationBar = QtWidgets.QSlider(parent=self.MediaPlayer)
        self.durationBar.setGeometry(QtCore.QRect(20, 540, 961, 20))
        self.durationBar.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: none;\n"
"    height: 6px;\n"
"    background: rgba(255, 255, 255, 0.3);\n"
"    border-radius: 3px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(229, 9, 20);\n"
"    border: none;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    border-radius: 6px;\n"
"    margin: -3px 0;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: rgb(229, 9, 20);\n"
"    border: none;\n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: rgba(255, 255, 255, 0.3);\n"
"    border: none;\n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"}")
        self.durationBar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.durationBar.setObjectName("durationBar")
        self.videoName = QtWidgets.QLabel(parent=self.MediaPlayer)
        self.videoName.setGeometry(QtCore.QRect(440, 590, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        self.videoName.setFont(font)
        self.videoName.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"}")
        self.videoName.setObjectName("videoName")
        self.volumeBtn = QtWidgets.QPushButton(parent=self.MediaPlayer)
        self.volumeBtn.setGeometry(QtCore.QRect(170, 580, 32, 32))
        self.volumeBtn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"    border-radius: 16px;\n"
"}")
        self.volumeBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/ThaiAn/Python-app/ui/../img/volume-high-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.volumeBtn.setIcon(icon4)
        self.volumeBtn.setIconSize(QtCore.QSize(24, 24))
        self.volumeBtn.setObjectName("volumeBtn")
        self.timeLabel = QtWidgets.QLabel(parent=self.MediaPlayer)
        self.timeLabel.setGeometry(QtCore.QRect(20, 520, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: transparent;\n"
"}")
        self.timeLabel.setObjectName("timeLabel")
        self.volumeBar = QtWidgets.QSlider(parent=self.MediaPlayer)
        self.volumeBar.setGeometry(QtCore.QRect(210, 586, 100, 20))
        self.volumeBar.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: none;\n"
"    height: 4px;\n"
"    background: rgba(255, 255, 255, 0.3);\n"
"    border-radius: 2px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: white;\n"
"    border: none;\n"
"    width: 8px;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"    margin: -2px 0;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: white;\n"
"    border: none;\n"
"    height: 4px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: rgba(255, 255, 255, 0.3);\n"
"    border: none;\n"
"    height: 4px;\n"
"    border-radius: 2px;\n"
"}")
        self.volumeBar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volumeBar.setObjectName("volumeBar")
        self.playBtn = QtWidgets.QPushButton(parent=self.MediaPlayer)
        self.playBtn.setGeometry(QtCore.QRect(90, 580, 32, 32))
        self.playBtn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"    border-radius: 16px;\n"
"}")
        self.playBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/ThaiAn/Python-app/ui/../img/play-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.playBtn.setIcon(icon5)
        self.playBtn.setIconSize(QtCore.QSize(24, 24))
        self.playBtn.setObjectName("playBtn")
        self.rewindBtn = QtWidgets.QPushButton(parent=self.MediaPlayer)
        self.rewindBtn.setGeometry(QtCore.QRect(50, 580, 32, 32))
        self.rewindBtn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"    border-radius: 16px;\n"
"}")
        self.rewindBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/ThaiAn/Python-app/ui/../img/repeat-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rewindBtn.setIcon(icon6)
        self.rewindBtn.setIconSize(QtCore.QSize(24, 24))
        self.rewindBtn.setObjectName("rewindBtn")
        self.forwardBtn = QtWidgets.QPushButton(parent=self.MediaPlayer)
        self.forwardBtn.setGeometry(QtCore.QRect(130, 580, 32, 32))
        self.forwardBtn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"    border-radius: 16px;\n"
"}")
        self.forwardBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/ThaiAn/Python-app/ui/../img/shuffle-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.forwardBtn.setIcon(icon7)
        self.forwardBtn.setIconSize(QtCore.QSize(24, 24))
        self.forwardBtn.setObjectName("forwardBtn")
        self.backBtn = QtWidgets.QPushButton(parent=self.MediaPlayer)
        self.backBtn.setGeometry(QtCore.QRect(10, 580, 32, 32))
        self.backBtn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"    border-radius: 16px;\n"
"}")
        self.backBtn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/ThaiAn/Python-app/ui/../img/thumbs-up-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.backBtn.setIcon(icon8)
        self.backBtn.setIconSize(QtCore.QSize(24, 24))
        self.backBtn.setObjectName("backBtn")
        self.stackedWidget.addWidget(self.MediaPlayer)
        self.Info = QtWidgets.QWidget()
        self.Info.setObjectName("Info")
        self.frame = QtWidgets.QFrame(parent=self.Info)
        self.frame.setGeometry(QtCore.QRect(229, 129, 601, 381))
        self.frame.setStyleSheet("border-radius: 30px;\n"
"background-color: rgb(56, 56, 56);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_15 = QtWidgets.QLabel(parent=self.frame)
        self.label_15.setGeometry(QtCore.QRect(60, 220, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.label_12 = QtWidgets.QLabel(parent=self.frame)
        self.label_12.setGeometry(QtCore.QRect(60, 270, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.txt_name = QtWidgets.QLineEdit(parent=self.frame)
        self.txt_name.setGeometry(QtCore.QRect(220, 130, 351, 31))
        self.txt_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"color: black;")
        self.txt_name.setText("")
        self.txt_name.setObjectName("txt_name")
        self.txt_email = QtWidgets.QLineEdit(parent=self.frame)
        self.txt_email.setGeometry(QtCore.QRect(220, 180, 351, 31))
        self.txt_email.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"color: black;")
        self.txt_email.setObjectName("txt_email")
        self.d_dob = QtWidgets.QDateEdit(parent=self.frame)
        self.d_dob.setGeometry(QtCore.QRect(220, 230, 351, 31))
        self.d_dob.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"color: black;")
        self.d_dob.setObjectName("d_dob")
        self.cb_gender = QtWidgets.QComboBox(parent=self.frame)
        self.cb_gender.setGeometry(QtCore.QRect(220, 270, 121, 31))
        self.cb_gender.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"color: black;")
        self.cb_gender.setObjectName("cb_gender")
        self.cb_gender.addItem("")
        self.cb_gender.addItem("")
        self.cb_gender.addItem("")
        self.btn_update_info = QtWidgets.QPushButton(parent=self.frame)
        self.btn_update_info.setGeometry(QtCore.QRect(240, 330, 100, 32))
        self.btn_update_info.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"color: black;")
        self.btn_update_info.setObjectName("btn_update_info")
        self.label_13 = QtWidgets.QLabel(parent=self.Info)
        self.label_13.setGeometry(QtCore.QRect(470, 80, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(22)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.Info)
        self.label_14.setGeometry(QtCore.QRect(290, 305, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.btn_avatar = QtWidgets.QPushButton(parent=self.Info)
        self.btn_avatar.setGeometry(QtCore.QRect(465, 140, 111, 110))
        self.btn_avatar.setStyleSheet("QPushButton {\n"
"    background-color: black;       /* Black background */\n"
"    border: 2px solid solid; /* Transparent border by default */\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;            /* Rounded corners */\n"
"    padding: 10px;                 /* Default padding */\n"
"    background-repeat: no-repeat; /* No repeating the image */\n"
"    background-position: center;  /* Center the icon */\n"
"    transition: all 0.2s ease;    /* Smooth transition */\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid white;       /* White border on hover */\n"
"    padding: 8px;                  /* Reduced padding to simulate size increase */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #333333;     /* Darker background on press */\n"
"    padding: 6px;                  /* Further reduced padding for pressed state */\n"
"}\n"
"")
        self.btn_avatar.setText("")
        self.btn_avatar.setObjectName("btn_avatar")
        self.label_16 = QtWidgets.QLabel(parent=self.Info)
        self.label_16.setGeometry(QtCore.QRect(290, 255, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.stackedWidget.addWidget(self.Info)
        self.nav_home_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.nav_home_btn.setGeometry(QtCore.QRect(100, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setBold(True)
        self.nav_home_btn.setFont(font)
        self.nav_home_btn.setStyleSheet("QPushButton {\n"
"    background-color: black;       /* Black background */\n"
"    border: 2px solid solid; /* Transparent border by default */\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;            /* Rounded corners */\n"
"    padding: 10px;                 /* Default padding */\n"
"    background-repeat: no-repeat; /* No repeating the image */\n"
"    background-position: center;  /* Center the icon */\n"
"    transition: all 0.2s ease;    /* Smooth transition */\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid white;       /* White border on hover */\n"
"    padding: 8px;                  /* Reduced padding to simulate size increase */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #333333;     /* Darker background on press */\n"
"    padding: 6px;                  /* Further reduced padding for pressed state */\n"
"}\n"
"")
        self.nav_home_btn.setObjectName("nav_home_btn")
        self.txt_search = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_search.setGeometry(QtCore.QRect(610, 20, 331, 41))
        self.txt_search.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"color: black;")
        self.txt_search.setObjectName("txt_search")
        self.stackedWidget.raise_()
        self.pushButton.raise_()
        self.nav_movie_btn.raise_()
        self.btn_mylist_btn.raise_()
        self.btn_search.raise_()
        self.nav_home_btn.raise_()
        self.txt_search.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nav_movie_btn.setText(_translate("MainWindow", "Movies"))
        self.btn_mylist_btn.setText(_translate("MainWindow", "My List"))
        self.btn_play_video.setText(_translate("MainWindow", "Play"))
        self.label_10.setText(_translate("MainWindow", "My List"))
        self.videoName.setText(_translate("MainWindow", "Video Name"))
        self.timeLabel.setText(_translate("MainWindow", "00:00:00/00:00:00"))
        self.label_15.setText(_translate("MainWindow", "Birthday:"))
        self.label_12.setText(_translate("MainWindow", "Gender:"))
        self.cb_gender.setItemText(0, _translate("MainWindow", "None"))
        self.cb_gender.setItemText(1, _translate("MainWindow", "Male"))
        self.cb_gender.setItemText(2, _translate("MainWindow", "Female"))
        self.btn_update_info.setText(_translate("MainWindow", "Save"))
        self.label_13.setText(_translate("MainWindow", "User info"))
        self.label_14.setText(_translate("MainWindow", "Email:"))
        self.label_16.setText(_translate("MainWindow", "Username:"))
        self.nav_home_btn.setText(_translate("MainWindow", "Account"))
