# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA07/FINAL PROJECT/ThaiAn/Python-app/ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.password_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(300, 380, 471, 61))
        font = QtGui.QFont()
        font.setFamily("Geist Semibold")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.password_input.setFont(font)
        self.password_input.setStyleSheet("    border: 1px solid #cccccc; /* Light gray border */\n"
"    border-radius: 30px; /* Rounded corners */\n"
"    background-color: rgba(255, 255, 255, 0.1); /* Transparent-like background */\n"
"    padding: 15px; /* Padding to create space around the text */\n"
"    color: white; /* Text color */\n"
"    font: 20px \"Geist Semibold\"; /* Font family and size */")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_input.setObjectName("password_input")
        self.email_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.email_input.setGeometry(QtCore.QRect(300, 290, 471, 61))
        font = QtGui.QFont()
        font.setFamily("Geist Semibold")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.email_input.setFont(font)
        self.email_input.setStyleSheet("    border: 1px solid #cccccc; /* Light gray border */\n"
"    border-radius: 30px; /* Rounded corners */\n"
"    background-color: rgba(255, 255, 255, 0.1); /* Transparent-like background */\n"
"    padding: 15px; /* Padding to create space around the text */\n"
"    color: white; /* Text color */\n"
"    font: 20px \"Geist Semibold\"; /* Font family and size */")
        self.email_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.email_input.setObjectName("email_input")
        self.login_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.login_btn.setGeometry(QtCore.QRect(270, 520, 541, 61))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(-1)
        font.setBold(True)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("  background-color: rgb(38, 41, 108); /* Light peach color */\n"
"    border: none;\n"
"    border-radius: 30px; /* Rounded corners */\n"
"    padding: 10px 20px; /* Padding for better appearance */\n"
"    font-size: 20px; /* Font size to make text readable */\n"
"    font-weight: bold;\n"
"    color: rgb(255, 255, 255); /* White text color */\n"
"    cursor: pointer;\n"
"    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); /* Light shadow for depth */\n"
"    transition: all 0.3s ease-in-out; /* Smooth transition for hover effects */")
        self.login_btn.setObjectName("login_btn")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(270, 480, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(-1)
        font.setBold(True)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("    spacing: 8px;                  /* Space between the checkbox indicator and label */\n"
"    color: ;                /* Peach color for the label text */\n"
"color: rgb(255, 255, 255);\n"
"    font-size: 20px;               /* Font size for the label text */\n"
"    font-weight: bold; ")
        self.checkBox.setObjectName("checkBox")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 475, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("background: none; /* No background */\n"
"    border: none; /* No border */\n"
"    color: rgb(255, 255, 255); /* White text color to match the background */\n"
"    font-size: 20px; /* Small, readable text */\n"
"    cursor: pointer; /* Pointer cursor to indicate clickability */\n"
"    text-decoration: none; /* Remove underline */\n"
"    font-weight: bold; /* Make the text bold for visibility */\n"
"    transition: color 0.3s ease, text-decoration 0.3s ease; /* Smooth transition for hover effects */")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-20, 0, 1121, 768))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/FINAL PROJECT/ThaiAn/Python-app/ui/../img/login_bg.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 50, 221, 221))
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/FINAL PROJECT/ThaiAn/Python-app/ui/../img/LOGO.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(490, 230, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setPointSize(-1)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("display: block; /* To make it take up its own line */\n"
"    text-align: center; /* Center the label */\n"
"    font-size: 35px; /* Medium font size for readability */\n"
"    color: #ffffff; /* White color to stand out against background */\n"
"    font-weight: normal; /* Normal weight to keep it subtle */")
        self.label_5.setObjectName("label_5")
        self.register_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.register_btn.setGeometry(QtCore.QRect(260, 580, 251, 29))
        font = QtGui.QFont()
        font.setFamily("Geist SemiBold")
        font.setBold(True)
        self.register_btn.setFont(font)
        self.register_btn.setStyleSheet("    background: none; /* Removes background */\n"
"    border: none;     /* Removes border */\n"
"    padding: 0;       /* Removes padding */\n"
"    outline: none;    /* Removes focus outline */\n"
"    color: white;   /* Keeps text color consistent */")
        self.register_btn.setObjectName("register_btn")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(250, 90, 581, 531))
        self.frame.setStyleSheet("    border: 2px solid #cccccc; /* Light gray border */\n"
"    border-radius: 30px; /* Rounded corners */\n"
"    background-color: rgba(255, 255, 255, 0.1); /* Transparent-like background */\n"
"    padding: 15px; /* Padding to create space around the text */\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.eye_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.eye_btn.setGeometry(QtCore.QRect(690, 395, 83, 29))
        self.eye_btn.setStyleSheet("    border: 0px solid #cccccc; /* Light gray border */\n"
"    border-radius: 30px; /* Rounded corners */\n"
"    background-color: rgba(255, 255, 255, 0); /* Transparent-like background */\n"
"    padding: 15px; /* Padding to create space around the text */\n"
"    color: white; /* Text color */\n"
"    font: 20px \"Segoe UI\"; /* Font family and size */")
        self.eye_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/FINAL PROJECT/ThaiAn/Python-app/ui/../img/eye-slash-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.eye_btn.setIcon(icon)
        self.eye_btn.setIconSize(QtCore.QSize(30, 30))
        self.eye_btn.setObjectName("eye_btn")
        self.label.raise_()
        self.frame.raise_()
        self.label_2.raise_()
        self.password_input.raise_()
        self.email_input.raise_()
        self.login_btn.raise_()
        self.checkBox.raise_()
        self.pushButton_2.raise_()
        self.label_5.raise_()
        self.register_btn.raise_()
        self.eye_btn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.password_input.setPlaceholderText(_translate("MainWindow", "Password"))
        self.email_input.setPlaceholderText(_translate("MainWindow", "Email"))
        self.login_btn.setText(_translate("MainWindow", "LOGIN"))
        self.checkBox.setText(_translate("MainWindow", "Remember Me"))
        self.pushButton_2.setText(_translate("MainWindow", "Forgot Password"))
        self.label_5.setText(_translate("MainWindow", "Log in"))
        self.register_btn.setText(_translate("MainWindow", "Don\'t have account? Register!"))
