# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA07/ThaiAn/Python-app/ui/movie_item.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MovieItem(object):
    def setupUi(self, MovieItem):
        MovieItem.setObjectName("MovieItem")
        MovieItem.resize(300, 400)
        MovieItem.setMinimumSize(QtCore.QSize(300, 400))
        MovieItem.setMaximumSize(QtCore.QSize(300, 400))
        MovieItem.setStyleSheet("QWidget#MovieItem {\n"
"    background-color: black;\n"
"    border: 1px solid rgba(255, 255, 255, 0.8);\n"
"    border-radius: 15px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(MovieItem)
        self.verticalLayout.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bannerLabel = QtWidgets.QLabel(parent=MovieItem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bannerLabel.sizePolicy().hasHeightForWidth())
        self.bannerLabel.setSizePolicy(sizePolicy)
        self.bannerLabel.setMinimumSize(QtCore.QSize(300, 300))
        self.bannerLabel.setStyleSheet("border-top-left-radius: 15px;\n"
"border-top-right-radius: 15px;")
        self.bannerLabel.setText("")
        self.bannerLabel.setScaledContents(True)
        self.bannerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.bannerLabel.setObjectName("bannerLabel")
        self.verticalLayout.addWidget(self.bannerLabel)
        self.titleLabel = QtWidgets.QLabel(parent=MovieItem)
        self.titleLabel.setStyleSheet("color: white;\n"
"font-family: Geist;\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"padding: 0 10px;")
        self.titleLabel.setText("")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setWordWrap(True)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setContentsMargins(10, -1, 10, -1)
        self.buttonLayout.setSpacing(5)
        self.buttonLayout.setObjectName("buttonLayout")
        self.playButton = QtWidgets.QPushButton(parent=MovieItem)
        self.playButton.setMinimumSize(QtCore.QSize(40, 40))
        self.playButton.setMaximumSize(QtCore.QSize(40, 40))
        self.playButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(229, 9, 20);\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    padding: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(193, 17, 25);\n"
"}")
        self.playButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/ThaiAn/Python-app/ui/../img/play-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.playButton.setIcon(icon)
        self.playButton.setIconSize(QtCore.QSize(24, 24))
        self.playButton.setObjectName("playButton")
        self.buttonLayout.addWidget(self.playButton)
        self.infoButton = QtWidgets.QPushButton(parent=MovieItem)
        self.infoButton.setMinimumSize(QtCore.QSize(40, 40))
        self.infoButton.setMaximumSize(QtCore.QSize(40, 40))
        self.infoButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(42, 42, 42, 0.7);\n"
"    border: 1px solid rgba(255, 255, 255, 0.7);\n"
"    border-radius: 20px;\n"
"    padding: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}")
        self.infoButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/ThaiAn/Python-app/ui/../img/circle-info-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.infoButton.setIcon(icon1)
        self.infoButton.setIconSize(QtCore.QSize(24, 24))
        self.infoButton.setObjectName("infoButton")
        self.buttonLayout.addWidget(self.infoButton)
        self.addButton = QtWidgets.QPushButton(parent=MovieItem)
        self.addButton.setMinimumSize(QtCore.QSize(40, 40))
        self.addButton.setMaximumSize(QtCore.QSize(40, 40))
        self.addButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(42, 42, 42, 0.7);\n"
"    border: 1px solid rgba(255, 255, 255, 0.7);\n"
"    border-radius: 20px;\n"
"    padding: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}")
        self.addButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/ThaiAn/Python-app/ui/../img/plus-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.addButton.setIcon(icon2)
        self.addButton.setIconSize(QtCore.QSize(24, 24))
        self.addButton.setObjectName("addButton")
        self.buttonLayout.addWidget(self.addButton)
        self.btn_favorite = QtWidgets.QPushButton(parent=MovieItem)
        self.btn_favorite.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_favorite.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_favorite.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_favorite.setStyleSheet("QPushButton {\n"
"    background-color: rgba(42, 42, 42, 0.7);\n"
"    border: 1px solid rgba(255, 255, 255, 0.7);\n"
"    border-radius: 20px;\n"
"    padding: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}")
        self.btn_favorite.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA07/ThaiAn/Python-app/ui/../img/heart-regular.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_favorite.setIcon(icon3)
        self.btn_favorite.setIconSize(QtCore.QSize(24, 24))
        self.btn_favorite.setObjectName("btn_favorite")
        self.buttonLayout.addWidget(self.btn_favorite)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(MovieItem)
        QtCore.QMetaObject.connectSlotsByName(MovieItem)

    def retranslateUi(self, MovieItem):
        pass
